import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { launchImageLibrary } from 'react-native-image-picker';
import AppButton from '../../components/AppButton';
import AppCard from '../../components/AppCard';
import AppHeader from '../../components/AppHeader';
import AppInput from '../../components/AppInput';
import KeyboardAvoid from '../../components/KeyboardAvoid';
import { buildingApi } from '../../api/buildingApi';
import { tenantApi } from '../../api/tenantApi';
import { colors } from '../../utils/constants';
import { getMessage } from '../../utils/helpers';

const today = () => { const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10); };
const initialForm=()=>({name:'',phone:'',email:'',fatherName:'',fatherPhone:'',permanentAddress:'',joiningDate:today(),rentAmount:'',advanceAmount:''});
const STEPS=[['Personal','account-outline'],['Documents','file-document-outline'],['Allocation','bed-outline']];

function SelectChip({label,selected,onPress,disabled}) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.chip,selected&&styles.chipActive,disabled&&styles.disabled]}><Text style={[styles.chipText,selected&&styles.chipTextActive]}>{label}</Text></Pressable>; }

function DocumentPicker({label,value,onPick,onRemove}) {
  return <View style={styles.document}><View style={styles.preview}>{value?.uri?<Image source={{uri:value.uri}} style={styles.previewImage}/>:<Icon name="image-outline" size={32} color={colors.muted}/>}</View><View style={styles.flex}><Text style={styles.documentTitle}>{label}</Text><Text style={styles.documentSub}>{value?value.name:'JPG, PNG or WEBP · max 5 MB'}</Text></View><Pressable style={[styles.docAction,value&&styles.docAdded]} onPress={value?onRemove:onPick}><Icon name={value?'check':'upload'} size={18} color={value?colors.success:colors.primary}/></Pressable></View>;
}

export default function AddCandidateScreen({navigation}) {
  const [step,setStep]=useState(1); const [form,setForm]=useState(initialForm); const [buildings,setBuildings]=useState([]); const [building,setBuilding]=useState(''); const [floor,setFloor]=useState(''); const [room,setRoom]=useState(''); const [bed,setBed]=useState(''); const [beds,setBeds]=useState([]); const [docs,setDocs]=useState({aadharFront:null,aadharBack:null,passportPhoto:null}); const [saving,setSaving]=useState(false); const [bedsLoading,setBedsLoading]=useState(false);
  const set=(key,value)=>setForm(prev=>({...prev,[key]:value}));
  useEffect(()=>{buildingApi.list().then(data=>setBuildings(Array.isArray(data)?data:[])).catch(error=>Alert.alert('Buildings',getMessage(error)));},[]);
  const selectedBuilding=buildings.find(item=>item._id===building); const floors=useMemo(()=>[...(selectedBuilding?.floors||[])].sort((a,b)=>a.floorNumber-b.floorNumber),[selectedBuilding]); const selectedFloor=floors.find(item=>item._id===floor); const rooms=selectedFloor?.rooms||[];
  useEffect(()=>{if(!building||!floor||!room){setBeds([]);return;}setBedsLoading(true);buildingApi.availableBeds(building,floor,room).then(data=>setBeds(data.availableBeds||[])).catch(()=>setBeds([])).finally(()=>setBedsLoading(false));},[building,floor,room]);

  const phoneError=value=>!/^\d{10}$/.test(value)||!/^[6-9]/.test(value)?'Phone must be 10 digits and start with 6, 7, 8 or 9.':null;
  const validatePersonal=()=>{
    if(!form.name.trim())return'Enter the tenant full name.'; if(phoneError(form.phone))return phoneError(form.phone); if(!/^\S+@\S+\.\S+$/.test(form.email))return'Enter a valid email address.'; if(!form.fatherName.trim())return"Enter the father's name."; if(phoneError(form.fatherPhone))return"Father's phone must be 10 digits and start with 6, 7, 8 or 9."; if(!form.permanentAddress.trim())return'Enter the permanent address.'; if(!form.joiningDate)return'Select the joining date.'; if(form.joiningDate>today())return'Future joining dates are not allowed.'; if(!Number(form.rentAmount)||Number(form.rentAmount)<=0)return'Enter a valid monthly rent.'; return null;
  };
  const next=()=>{if(step===1){const error=validatePersonal();if(error)return Alert.alert('Personal details',error);}if(step===2&&Object.values(docs).some(file=>!file))return Alert.alert('Documents required','Upload Aadhaar front, Aadhaar back and passport photo.');setStep(value=>Math.min(3,value+1));};
  const pick=key=>launchImageLibrary({mediaType:'photo',selectionLimit:1,includeBase64:false},result=>{if(result.didCancel)return;const asset=result.assets?.[0];if(!asset?.uri)return;if(Number(asset.fileSize||0)>5*1024*1024)return Alert.alert('File too large','Select an image smaller than 5 MB.');setDocs(prev=>({...prev,[key]:{uri:asset.uri,type:asset.type||'image/jpeg',name:asset.fileName||`${key}.jpg`}}));});
  const submit=async()=>{const personalError=validatePersonal();if(personalError)return Alert.alert('Personal details',personalError);if(Object.values(docs).some(file=>!file))return Alert.alert('Documents required','Upload all three required documents.');if(!building||!floor||!room||!bed)return Alert.alert('Allocation required','Select a building, floor, room and available bed.');const fd=new FormData();Object.entries(form).forEach(([key,value])=>fd.append(key,key==='advanceAmount'?String(Number(value||0)):value));fd.append('buildingId',building);fd.append('floorId',floor);fd.append('roomId',room);fd.append('bedId',bed);Object.entries(docs).forEach(([key,file])=>fd.append(key,file));setSaving(true);try{await tenantApi.create(fd);Alert.alert('Candidate added','Tenant added successfully with room allocation.',[{text:'Done',onPress:()=>navigation.goBack()}]);}catch(error){Alert.alert('Unable to add candidate',getMessage(error));}finally{setSaving(false);}};

  return <View style={styles.screen}><AppHeader title="Add New Tenant" subtitle="Complete registration and allocation" onBack={()=>navigation.goBack()}/><KeyboardAvoid style={styles.flex}><ScrollView contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <View style={styles.steps}>{STEPS.map(([label,icon],index)=>{const number=index+1;const done=step>number;const active=step===number;return <React.Fragment key={label}><Pressable disabled={number>step} onPress={()=>number<step&&setStep(number)} style={styles.step}><View style={[styles.stepCircle,(active||done)&&styles.stepCircleActive,done&&styles.stepDone]}><Icon name={done?'check':icon} size={18} color={(active||done)?'#fff':colors.muted}/></View><Text style={[styles.stepLabel,active&&styles.stepLabelActive]}>{label}</Text></Pressable>{number<3?<View style={[styles.stepLine,step>number&&styles.stepLineDone]}/>:null}</React.Fragment>})}</View>
    {step===1?<AppCard><View style={styles.cardTitleRow}><Icon name="account-outline" size={22} color={colors.primary}/><Text style={styles.cardTitle}>Personal Details</Text></View><AppInput label="Full Name *" value={form.name} onChangeText={v=>set('name',v)}/><AppInput label="Phone *" value={form.phone} onChangeText={v=>/^\d{0,10}$/.test(v)&&set('phone',v)} keyboardType="phone-pad"/><AppInput label="Email *" value={form.email} onChangeText={v=>set('email',v)} keyboardType="email-address" autoCapitalize="none"/><View style={styles.twoColumn}><View style={styles.flex}><AppInput label="Father's Name *" value={form.fatherName} onChangeText={v=>set('fatherName',v)}/></View><View style={styles.flex}><AppInput label="Father's Phone *" value={form.fatherPhone} onChangeText={v=>/^\d{0,10}$/.test(v)&&set('fatherPhone',v)} keyboardType="phone-pad"/></View></View><AppInput label="Permanent Address *" value={form.permanentAddress} onChangeText={v=>set('permanentAddress',v)} multiline/><AppInput label="Joining Date (YYYY-MM-DD) *" value={form.joiningDate} onChangeText={v=>set('joiningDate',v)}/><View style={styles.twoColumn}><View style={styles.flex}><AppInput label="Monthly Rent *" value={form.rentAmount} onChangeText={v=>set('rentAmount',v)} keyboardType="numeric"/></View><View style={styles.flex}><AppInput label="Advance Amount" value={form.advanceAmount} onChangeText={v=>set('advanceAmount',v)} keyboardType="numeric"/></View></View><AppButton title="Continue to Documents" icon="arrow-right" onPress={next}/></AppCard>:null}
    {step===2?<AppCard><View style={styles.cardTitleRow}><Icon name="file-document-outline" size={22} color={colors.primary}/><View><Text style={styles.cardTitle}>Required Documents</Text><Text style={styles.muted}>All three documents are mandatory</Text></View></View><DocumentPicker label="Aadhaar Card - Front" value={docs.aadharFront} onPick={()=>pick('aadharFront')} onRemove={()=>setDocs(prev=>({...prev,aadharFront:null}))}/><DocumentPicker label="Aadhaar Card - Back" value={docs.aadharBack} onPick={()=>pick('aadharBack')} onRemove={()=>setDocs(prev=>({...prev,aadharBack:null}))}/><DocumentPicker label="Passport Size Photo" value={docs.passportPhoto} onPick={()=>pick('passportPhoto')} onRemove={()=>setDocs(prev=>({...prev,passportPhoto:null}))}/><View style={styles.actions}><AppButton title="Back" icon="arrow-left" variant="secondary" style={styles.flex} onPress={()=>setStep(1)}/><AppButton title="Continue" icon="arrow-right" style={styles.flex} onPress={next}/></View></AppCard>:null}
    {step===3?<AppCard><View style={styles.cardTitleRow}><Icon name="bed-outline" size={22} color={colors.primary}/><View><Text style={styles.cardTitle}>Room Allocation</Text><Text style={styles.muted}>Select an available bed</Text></View></View><Text style={styles.fieldLabel}>Building *</Text><View style={styles.chips}>{buildings.map(item=><SelectChip key={item._id} label={item.buildingName} selected={building===item._id} onPress={()=>{setBuilding(item._id);setFloor('');setRoom('');setBed('');}}/>)}</View><Text style={styles.fieldLabel}>Floor *</Text><View style={styles.chips}>{floors.map(item=><SelectChip key={item._id} label={`Floor ${item.floorNumber}`} selected={floor===item._id} onPress={()=>{setFloor(item._id);setRoom('');setBed('');}}/>)}</View><Text style={styles.fieldLabel}>Room *</Text><View style={styles.chips}>{rooms.map(item=><SelectChip key={item._id} label={`Room ${item.roomNumber} · ${item.shareType}-share`} selected={room===item._id} onPress={()=>{setRoom(item._id);setBed('');}}/>)}</View><Text style={styles.fieldLabel}>Available Bed *</Text>{bedsLoading?<Text style={styles.muted}>Loading available beds...</Text>:<View style={styles.chips}>{beds.map(item=><SelectChip key={item._id} label={`Bed ${item.bedNumber}`} selected={bed===item._id} onPress={()=>setBed(item._id)}/>)}</View>}{room&&!bedsLoading&&!beds.length?<Text style={styles.error}>No available beds in this room.</Text>:null}<View style={styles.summary}><Icon name="check-decagram-outline" size={20} color={colors.success}/><Text style={styles.summaryText}>{building&&floor&&room&&bed?'Allocation complete. Ready to save.':'Complete every allocation selection.'}</Text></View><View style={styles.actions}><AppButton title="Back" icon="arrow-left" variant="secondary" style={styles.flex} onPress={()=>setStep(2)}/><AppButton title="Save Tenant" icon="account-check-outline" loading={saving} style={styles.flex} onPress={submit}/></View></AppCard>:null}<View style={styles.footer}/>
  </ScrollView></KeyboardAvoid></View>;
}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},body:{padding:16},flex:{flex:1},footer:{height:20},steps:{flexDirection:'row',alignItems:'center',justifyContent:'center',marginBottom:15},step:{alignItems:'center',gap:4},stepCircle:{width:38,height:38,borderRadius:19,backgroundColor:colors.faint,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},stepCircleActive:{backgroundColor:colors.primary,borderColor:colors.primary},stepDone:{backgroundColor:colors.success,borderColor:colors.success},stepLabel:{fontSize:9,color:colors.muted,fontWeight:'700'},stepLabelActive:{color:colors.primary},stepLine:{width:34,height:2,backgroundColor:colors.border,marginHorizontal:5,marginBottom:16},stepLineDone:{backgroundColor:colors.success},cardTitleRow:{flexDirection:'row',alignItems:'center',gap:9,marginBottom:9},cardTitle:{fontSize:17,color:colors.text,fontWeight:'900'},muted:{fontSize:11,color:colors.muted,marginTop:2},twoColumn:{flexDirection:'row',gap:10},document:{flexDirection:'row',alignItems:'center',gap:10,padding:10,borderWidth:1,borderColor:colors.border,borderRadius:13,marginBottom:10},preview:{width:52,height:52,borderRadius:10,backgroundColor:colors.faint,alignItems:'center',justifyContent:'center',overflow:'hidden'},previewImage:{width:'100%',height:'100%'},documentTitle:{fontSize:13,color:colors.text,fontWeight:'800'},documentSub:{fontSize:9,color:colors.muted,marginTop:3},docAction:{width:37,height:37,borderRadius:10,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},docAdded:{backgroundColor:colors.successSoft},actions:{flexDirection:'row',gap:10,marginTop:4},fieldLabel:{fontSize:10,color:colors.muted,fontWeight:'900',textTransform:'uppercase',marginTop:8,marginBottom:7},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,minHeight:8},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:9,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},chipActive:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontSize:11,color:colors.text,fontWeight:'800'},chipTextActive:{color:'#fff'},disabled:{opacity:.45},error:{fontSize:11,color:colors.danger,marginTop:6},summary:{flexDirection:'row',alignItems:'center',gap:8,padding:11,borderRadius:11,backgroundColor:colors.successSoft,marginVertical:14},summaryText:{fontSize:11,color:colors.success,fontWeight:'800'}});
